#!/bin/bash

read -p "Compile and run or just run (1/2) -> " modo

if [ "$modo" == "1" ]; then
    echo "Compiling..."
    cd src
    make
    echo "Finished, running..."
    make run
    echo "Cleaning..."
    make clean
    cd ..


elif [ "$modo" == "2" ]; then
    cd src
    if ! ls | grep os-image.bin; then
        echo "There is no os-image.bin in src, closing..."
        exit -1

    else
        make
        cd ..

    fi

else
    echo "Wtf bro (-> -_-)->"
    exit -1

fi
